"""Add password reset fields

Revision ID: 0f6acfcf172f
Revises: 0cbf77e9bec3
Create Date: 2026-02-16 16:08:31.773814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6acfcf172f'
down_revision = '0cbf77e9bec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_reset_token_hash'), ['reset_token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token_hash'))
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token_hash')

    # ### end Alembic commands ###
